### ISSUE TITLE
Save action's environment variables to a file

### ISSUE THREAD

**Issue by rabbah** [nimbella/aio-cli-plugin-runtime#16]
Add `--save-env (-E)` to save any attached environment variables to a file. This is convenient for recreating a `dotenv` file, editing it and redeploying a project.

**Comment by rabbah** [comment]
Implemented in https://github.com/nimbella/aio-cli-plugin-runtime/commit/7814c429e279a4bf490fc97faccf7e9bdb9791e1.

**Comment by joshuaauerbachwatson** [comment]
It is my impression that this has been implemented.  @rabbah ?
