### ISSUE TITLE
add new --url like flag on action get to show both .json and naked url

### ISSUE THREAD

**Issue by rabbah** [nimbella/aio-cli-plugin-runtime#7]
I opened https://github.com/adobe/aio-cli-plugin-runtime/issues/189 and ideally we can contribute the change upstream .

**Comment by rabbah** [comment]
There may not be appetite for this upstream. I am not sure I like my original suggestion either.
Do we want to do anything about this or close?

**Comment by joshuaauerbachwatson** [comment]
There's not a lot of information about what you were proposing, anyway, but I favor closing as we generally have lot of options in this part of the command tree and it might be that less is more unless this will be really pivotal in the customer experience.

**Comment by rabbah** [comment]
For reference, the details are in the linked issue upstream.
